version: '3'

services:

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:1.25
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  web:
    image: nginx:latest
    ports:
      - "8097:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jean1804
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  jenkins_home: